name: beta

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export JQ_VERSION=$(curl -sSL https://api.github.com/repos/stedolan/jq/tags | jq -r "[.[].name] | .[0] | sub(\"jq-\";\"\")")
          echo "JQ_VERSION=${JQ_VERSION}" >> $GITHUB_ENV
          echo "Version: ${JQ_VERSION}"
      - name: Build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg JQ_VERSION="${JQ_VERSION}" \
            -f Dockerfile \
            -t truemark/jq:beta-${JQ_VERSION} \
            -t truemark/jq:beta \
            .
          IMAGE="truemark/jq:beta-${JQ_VERSION}" ARCH="amd64" FILE="jq-linux-amd64" ./getlayer.sh
          IMAGE="truemark/jq:beta-${JQ_VERSION}" ARCH="arm64" FILE="jq-linux-arm64" ./getlayer.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: files
          path: |
            jq-*
